- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add CRI-O apt key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ crio_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/cri-o-apt-keyring.asc
    mode: "0644"

- name: Add CRI-O repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.asc] https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ crio_version }}/deb/ /"
    filename: cri-o
    state: present

- name: Install CRI-O
  ansible.builtin.apt:
    name: cri-o
    state: present
    update_cache: true

- name: Enable and start CRI-O
  ansible.builtin.systemd:
    name: crio
    enabled: true
    state: started

