all:
  children:
    k8s_control_plane:
      hosts:
        k8s-master-01:
          ansible_host: 192.168.56.10
    k8s_workers:
      hosts:
        k8s-worker-01:
          ansible_host: 192.168.56.11
        k8s-worker-02:
          ansible_host: 192.168.56.12
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:

